name: book_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  toast: ^0.3.0
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_no_words_light_mode.png
    - assets/logo_no_words_dark_mode.png
    - assets/logo_words_light_mode.png
    - assets/logo_words_dark_mode.png
    - assets/settings_icon_light_mode.png
    - assets/settings_icon_dark_mode.png