import 'package:flutter/material.dart';
import 'package:book_buddy/login.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color.fromARGB(92, 216, 243, 245)),
        useMaterial3: true,
      ),
      home: StartUpPage(),  
    );
  }
}

class StartUpPage extends StatelessWidget {
  const StartUpPage ({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color.fromARGB(92, 216, 243, 245),
      body: Align(  // Align everything at the top
        alignment: Alignment.topCenter,  // Move everything to the top
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,  // Center horizontally
          children: [
            // Add in the logo.
            SizedBox(
              width: 500,
              height: 500,
              child: Image.asset('assets/logo_with_words.png'),
            ),

            // Add space between the logo and the button.
            SizedBox(height: 10),  

            // Add the "Get Started!" button and navigate to Login page.
            ElevatedButton(
              onPressed: () {
                // Navigate to the Login page when the button is pressed
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => Login()),  // Navigate to LoginPage
                );
              },
              style: ElevatedButton.styleFrom(
                /*
                  The code for the styling of this button was in part generated by AI.
                  AI was used for finding out how to change the background, foreground and
                  shadow colours of the button.
                  */
                minimumSize: Size(200, 70),  
                padding: EdgeInsets.symmetric(horizontal: 40, vertical: 20),  
                textStyle: TextStyle(fontSize: 18),  // Font size of the text
                backgroundColor: Color.fromARGB(255, 216, 238, 245), // Button background color
                foregroundColor: Colors.black, // Text color
                shadowColor: Colors.blueAccent, // Shadow color (optional)
              ),
              child: Text('Get Started!'),
            ),
          ],
        ),
      ),
    );
  }
}
