import 'package:flutter/material.dart';
import 'package:book_buddy/screens/login.dart';
import 'package:book_buddy/screens/settings.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  _MyAppState createState() => _MyAppState();
}

/*
AI was used to help make the light/dark mode settings.
Firstly by helping make the toggle in the settings page, then by
making the settings global.
*/
class _MyAppState extends State<MyApp>{
  bool isDarkMode = false;

  // Method to toggle to dark mode
  void toggleDarkMode(bool value){
    setState((){
      isDarkMode = value;
    });
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color.fromARGB(92, 216, 243, 245)),
        useMaterial3: true,
      ),
      home: StartUpPage(
        isDarkMode: isDarkMode,
        toggleDarkMode: toggleDarkMode,
      ),  
    );
  }
}

class StartUpPage extends StatelessWidget {
  final bool isDarkMode;
  final Function(bool) toggleDarkMode;

  const StartUpPage ({super.key, required this.isDarkMode, required this.toggleDarkMode});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: isDarkMode ? Color.fromARGB(255, 20, 9, 45) : Color.fromARGB(255, 216, 243, 245),
      body: Align(  // Align everything at the top
        alignment: Alignment.topCenter,  // Move everything to the top
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,  // Center horizontally
          children: [
            // Add in the logo.
            SizedBox(
              width: 500,
              height: 500,
              child: Image.asset('assets/logo_with_words.png'),
            ),

            // Add space between the logo and the button.
            SizedBox(height: 10),  

            // Add the "Get Started!" button and navigate to Login page.
            ElevatedButton(
              onPressed: () {
                // Navigate to the Login page when the button is pressed
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => Login()),  // Navigate to LoginPage
                );
              },
              style: ElevatedButton.styleFrom(
                /*
                  The code for the styling of this button was in part generated by AI.
                  AI was used for finding out how to change the background, foreground and
                  shadow colours of the button.
                  */
                minimumSize: Size(200, 70),  
                padding: EdgeInsets.symmetric(horizontal: 40, vertical: 20),  
                textStyle: TextStyle(fontSize: 18),  // Font size of the text
                backgroundColor: Color.fromARGB(255, 216, 238, 245), // Button background color
                foregroundColor: Colors.black, // Text color
                shadowColor: Colors.blueAccent, // Shadow color (optional)
              ),
              child: Text('Get Started!'),
            ),

            ElevatedButton(
              onPressed: () {
                // Navigate to the Login page when the button is pressed
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => Settings(isDarkMode: isDarkMode, toggleDarkMode:  toggleDarkMode,)),  // Navigate to LoginPage
                );
              },
              style: ElevatedButton.styleFrom(
                /*
                  The code for the styling of this button was in part generated by AI.
                  AI was used for finding out how to change the background, foreground and
                  shadow colours of the button.
                  */
                minimumSize: Size(200, 70),  
                padding: EdgeInsets.symmetric(horizontal: 40, vertical: 20),  
                textStyle: TextStyle(fontSize: 18),  // Font size of the text
                backgroundColor: Color.fromARGB(255, 216, 238, 245), // Button background color
                foregroundColor: Colors.black, // Text color
                shadowColor: Colors.blueAccent, // Shadow color (optional)
              ),
              child: Text('settings'),
            ),
          ],
        ),
      ),
    );
  }
}
