apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services' // If using Firebase

android {
    compileSdkVersion 34

    defaultConfig {
        applicationId "com.example.book_buddy"
        minSdkVersion 23  
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version" // If using Kotlin
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    // Add other dependencies here
}
